const mockData = [
  {
    name: "Emma Johnson",
    email: "emma.johnson@example.com",
    date: "2024-12-01",
    time: "10:15 AM",
    status: "Active",
  },
  {
    name: "Liam Smith",
    email: "liam.smith@example.com",
    date: "2024-12-02",
    time: "02:30 PM",
    status: "Inactive",
  },
  {
    name: "Olivia Brown",
    email: "olivia.brown@example.com",
    date: "2024-12-03",
    time: "09:45 AM",
    status: "Pending",
  },
  {
    name: "Noah Williams",
    email: "noah.williams@example.com",
    date: "2024-12-04",
    time: "11:00 AM",
    status: "Active",
  },
  {
    name: "Ava Jones",
    email: "ava.jones@example.com",
    date: "2024-12-05",
    time: "03:45 PM",
    status: "Inactive",
  },
  {
    name: "Sophia Garcia",
    email: "sophia.garcia@example.com",
    date: "2024-12-06",
    time: "01:30 PM",
    status: "Active",
  },
  {
    name: "Elijah Martinez",
    email: "elijah.martinez@example.com",
    date: "2024-12-01",
    time: "12:15 PM",
    status: "Pending",
  },
  {
    name: "Isabella Hernandez",
    email: "isabella.hernandez@example.com",
    date: "2024-12-02",
    time: "04:45 PM",
    status: "Active",
  },
  {
    name: "James Lopez",
    email: "james.lopez@example.com",
    date: "2024-12-03",
    time: "08:30 AM",
    status: "Inactive",
  },
  {
    name: "Mia Wilson",
    email: "mia.wilson@example.com",
    date: "2024-12-04",
    time: "05:00 PM",
    status: "Pending",
  },
  {
    name: "Benjamin Anderson",
    email: "benjamin.anderson@example.com",
    date: "2024-12-05",
    time: "09:15 AM",
    status: "Active",
  },
  {
    name: "Charlotte Thomas",
    email: "charlotte.thomas@example.com",
    date: "2024-12-06",
    time: "10:45 AM",
    status: "Inactive",
  },
  {
    name: "Lucas Taylor",
    email: "lucas.taylor@example.com",
    date: "2024-12-01",
    time: "01:00 PM",
    status: "Active",
  },
  {
    name: "Amelia Moore",
    email: "amelia.moore@example.com",
    date: "2024-12-02",
    time: "02:15 PM",
    status: "Pending",
  },
  {
    name: "Henry Jackson",
    email: "henry.jackson@example.com",
    date: "2024-12-03",
    time: "04:00 PM",
    status: "Inactive",
  },
  {
    name: "Harper White",
    email: "harper.white@example.com",
    date: "2024-12-04",
    time: "11:30 AM",
    status: "Active",
  },
  {
    name: "Alexander Harris",
    email: "alexander.harris@example.com",
    date: "2024-12-05",
    time: "03:00 PM",
    status: "Pending",
  },
  {
    name: "Evelyn Clark",
    email: "evelyn.clark@example.com",
    date: "2024-12-06",
    time: "09:30 AM",
    status: "Inactive",
  },
  {
    name: "William Lewis",
    email: "william.lewis@example.com",
    date: "2024-12-01",
    time: "12:45 PM",
    status: "Active",
  },
  {
    name: "Luna Young",
    email: "luna.young@example.com",
    date: "2024-12-02",
    time: "10:00 AM",
    status: "Pending",
  },
];

export default mockData;
